In [137]:
import tensorflow as tf
import numpy as np

Starting with the basic concepts of TF

In [138]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [139]:
tensor_bool = tf.constant([True, True, False])


In [140]:
tensor_one_d  = tf.constant([2.,0.,5.,6.], dtype=tf.float16)
casted_tensor = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [141]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,5],
    [5,6,7],
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [3 4 5]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [142]:
tensor_three_d = tf.constant([
[[1,2,3],
[3,4,5]],

[[1,2,3],
[3,4,5]],

[[1,2,3],
[3,4,5]],

])
print(tensor_three_d.shape)


(3, 2, 3)


In [143]:
four_d_tensor = tf.constant([
#First layer 
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
],
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
]]
)

In [144]:
np_array = np.array([13 ,46 ,7])
converted_tensor = tf.convert_to_tensor(np_array)

In [145]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=[2,4],
    dtype=tf.dtypes.bfloat16,
    name="eye"
)


In [146]:
fill_tensor =tf.fill([5,3,6],9)

ones_like = tf.ones_like (
fill_tensor
)

In [147]:
tensor_rank = tf.size(fill_tensor)
tensor_rank 


<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [148]:
reandowm_tensor = tf.random.normal(
    [3,4],
    mean=0.0,
    stddev=2.0,
    seed= 5
)
reandowm_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.6121852,  1.978791 , -0.6452092, -4.965141 ],
       [-1.4184582,  1.5928245, -2.5180225, -4.886535 ],
       [ 1.0408081, -0.2988072,  1.347326 ,  0.3292156]], dtype=float32)>

In [149]:
rend_uniform = tf.random.uniform(
    [3,5],
    maxval=10,
    minval=1,
)
rend_uniform

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[4.8526597, 3.086911 , 2.0376062, 3.7489262, 5.700284 ],
       [5.150039 , 8.209985 , 8.608425 , 4.7684574, 5.2633286],
       [4.0471344, 7.579784 , 6.0742064, 1.0862437, 5.3953414]],
      dtype=float32)>

In [150]:
tensor_index = tf.constant([1, 24, 56, 78 ,9, 5,66])
print(tensor_index)
print(tensor_index[-1::])


tf.Tensor([ 1 24 56 78  9  5 66], shape=(7,), dtype=int32)
tf.Tensor([66], shape=(1,), dtype=int32)


In [151]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,5],
    [5,6,7],
])

print(tensor_two_d[..., 0])

tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [152]:
four_d_tensor = tf.constant([
#First layer 
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
],
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
]]
)
print(tensor_three_d[0,...,0])

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [153]:
x_abs = tf.constant([-2.25,3.25])
print(tf.abs(x_abs))

tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)


In [154]:
x_abs_comp = tf.constant([-2.25 +3.25j])
print(tf.abs(x_abs_comp))



tf.Tensor([3.95284708], shape=(1,), dtype=float64)


In [155]:
x_1 = tf.constant([-2.25,3.25])
x_2 = tf.constant([6,23.25])
print(tf.add(x_1,x_2))

tf.Tensor([ 3.75 26.5 ], shape=(2,), dtype=float32)


In [156]:
x_args = tf.constant([[[2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,4, 5, 9, 71]
],
[                     [2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,102, 5, 9, 71]
]

])
print(tf.argmax(x_args,1))

tf.Tensor(
[[1 1 1 0 2 2]
 [1 1 2 0 2 2]], shape=(2, 6), dtype=int64)


In [157]:
power = tf.constant([[2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,4, 5, 9, 71]
])
#print(tf.pow(power,2))
print(tf.reduce_mean(power,axis=1,keepdims=False))

tf.Tensor([ 4  8 15], shape=(3,), dtype=int32)


In [158]:
print(tf.math.top_k(power, k=2))

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  6],
       [22,  6],
       [71,  9]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 4],
       [2, 1],
       [5, 4]], dtype=int32)>)


In [164]:
x_1 = tf.constant([[-2.25,3.25],
                   [6,23.25]])

x_2 = tf.constant([[6,23.25],
                   [-2.25,3.25]])
tf.linalg.matmul(x_1,x_2)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-20.8125, -41.75  ],
       [-16.3125, 215.0625]], dtype=float32)>

In [169]:
#transpose 
V = tf.constant([1, 2 ,3 ,4])
tf.transpose(V)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
A = np.array([[2, 6, 5, 2],
              [2, -2, 2, 3],
              [1, 5, 4, 0]])
B = np.array(
    [[0.42379562, 0.07614612, 0.30300833, 0.02341555],
 [0.58955559, 0.78879676, 0.35213701, 0.39180098],
 [0.766514,   0.23896911, 0.97578651, 0.58668112],
 [0.51967773, 0.26416732, 0.34514883, 0.58260508],
 [0.75930903, 0.35161298, 0.3642544, 0.88772801],
 [0.75930903, 0.35161298, 0.3642544, 0.88772801]])

print(A.shape)
print(B.shape)

print(np.matmul(A,B))

(3, 4)
(5, 4)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)