In [9]:
import tensorflow as tf
import numpy as np

Starting with the basic concepts of TF

In [10]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [11]:
tensor_bool = tf.constant([True, True, False])


In [12]:
tensor_one_d  = tf.constant([2.,0.,5.,6.], dtype=tf.float16)
casted_tensor = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [13]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,5],
    [5,6,7],
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [3 4 5]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [14]:
tensor_three_d = tf.constant([
[[1,2,3],
[3,4,5]],

[[1,2,3],
[3,4,5]],

[[1,2,3],
[3,4,5]],

])
print(tensor_three_d.shape)


(3, 2, 3)


In [15]:
four_d_tensor = tf.constant([
#First layer 
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
],
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
]]
)

In [16]:
np_array = np.array([13 ,46 ,7])
converted_tensor = tf.convert_to_tensor(np_array)

In [17]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=[2,4],
    dtype=tf.dtypes.bfloat16,
    name="eye"
)


In [18]:
fill_tensor =tf.fill([5,3,6],9)

ones_like = tf.ones_like (
fill_tensor
)

In [19]:
tensor_rank = tf.size(fill_tensor)
tensor_rank 


<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [20]:
reandowm_tensor = tf.random.normal(
    [3,4],
    mean=0.0,
    stddev=2.0,
    seed= 5
)
reandowm_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-2.3561656 , -1.4198828 , -3.496316  , -0.9907444 ],
       [ 0.48607776, -0.25262603, -1.3278574 , -0.99039674],
       [-1.7878686 , -3.593185  ,  0.8177471 , -2.403319  ]],
      dtype=float32)>

In [21]:
rend_uniform = tf.random.uniform(
    [3,5],
    maxval=10,
    minval=1,
)
rend_uniform

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[2.9434557, 4.114506 , 6.421711 , 3.5391302, 3.3483782],
       [5.247649 , 6.435074 , 6.487338 , 3.1533813, 1.0172627],
       [3.8688726, 2.972269 , 2.3446417, 7.494789 , 1.1592685]],
      dtype=float32)>

In [22]:
tensor_index = tf.constant([1, 24, 56, 78 ,9, 5,66])
print(tensor_index)
print(tensor_index[-1::])


tf.Tensor([ 1 24 56 78  9  5 66], shape=(7,), dtype=int32)
tf.Tensor([66], shape=(1,), dtype=int32)


In [23]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,5],
    [5,6,7],
])

print(tensor_two_d[..., 0])

tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [24]:
four_d_tensor = tf.constant([
#First layer 
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
],
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
]]
)
print(tensor_three_d[0,...,0])

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [25]:
x_abs = tf.constant([-2.25,3.25])
print(tf.abs(x_abs))

tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)


In [26]:
x_abs_comp = tf.constant([-2.25 +3.25j])
print(tf.abs(x_abs_comp))



tf.Tensor([3.95284708], shape=(1,), dtype=float64)


In [27]:
x_1 = tf.constant([-2.25,3.25])
x_2 = tf.constant([6,23.25])
print(tf.add(x_1,x_2))

tf.Tensor([ 3.75 26.5 ], shape=(2,), dtype=float32)


In [28]:
x_args = tf.constant([[[2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,4, 5, 9, 71]
],
[                     [2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,102, 5, 9, 71]
]

])
print(tf.argmax(x_args,1))

tf.Tensor(
[[1 1 1 0 2 2]
 [1 1 2 0 2 2]], shape=(2, 6), dtype=int64)


In [29]:
power = tf.constant([[2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,4, 5, 9, 71]
])
#print(tf.pow(power,2))
print(tf.reduce_mean(power,axis=1,keepdims=False))

tf.Tensor([ 4  8 15], shape=(3,), dtype=int32)


In [30]:
print(tf.math.top_k(power, k=2))

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  6],
       [22,  6],
       [71,  9]], dtype=int32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 4],
       [2, 1],
       [5, 4]], dtype=int32)>)


In [31]:
x_1 = tf.constant([[-2.25,3.25],
                   [6,23.25]])

x_2 = tf.constant([[6,23.25],
                   [-2.25,3.25]])
tf.linalg.matmul(x_1,x_2)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-20.8125, -41.75  ],
       [-16.3125, 215.0625]], dtype=float32)>

In [32]:
#transpose 
V = tf.constant([1, 2 ,3 ,4])
tf.transpose(V)


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [33]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])


print(A.shape)
print(B.shape)

print(np.matmul(A,B))


(3, 3)
(3, 3)
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [34]:
print(np.einsum('ij,jk -> ik', A,B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [35]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
print(np.einsum("ij,ij -> ij", A, B))


[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [37]:
A = np.array([
             [[1, 2, 3, 5],
              [4, 5, 6, 7],
              [7, 8, 9, 7]],

              [[1, 2, 3, 5],
              [4, 5, 6, 7],
              [7, 8, 9, 7]]
              ])
print(np.shape(A))
trns = np.einsum('bij -> bji', A)

print(trns)


(2, 3, 4)
[[[1 4 7]
  [2 5 8]
  [3 6 9]
  [5 7 7]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]
  [5 7 7]]]


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(np.einsum())

In [39]:
A = np.random.randn(2,4,4,2) # bcij
B = np.random.randn(2,4,4,1) # bcik
np.einsum("bcik,bcij -> bckj", B , A).shape 


(2, 4, 1, 2)