In [32]:
import tensorflow as tf
import numpy as np

Starting with the basic concepts of TF

In [33]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [34]:
tensor_bool = tf.constant([True, True, False])


In [35]:
tensor_one_d  = tf.constant([2.,0.,5.,6.], dtype=tf.float16)
casted_tensor = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [36]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,5],
    [5,6,7],
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [3 4 5]
 [5 6 7]], shape=(3, 3), dtype=int32)


In [37]:
tensor_three_d = tf.constant([
[[1,2,3],
[3,4,5]],

[[1,2,3],
[3,4,5]],

[[1,2,3],
[3,4,5]],

])
print(tensor_three_d.shape)


(3, 2, 3)


In [38]:
four_d_tensor = tf.constant([
#First layer 
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
],
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
]]
)

In [41]:
np_array = np.array([13 ,46 ,7])
converted_tensor = tf.convert_to_tensor(np_array)

In [49]:
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=5,
    batch_shape=[2,4],
    dtype=tf.dtypes.bfloat16,
    name="eye"
)


In [55]:
fill_tensor =tf.fill([5,3,6],9)

ones_like = tf.ones_like (
fill_tensor
)

In [59]:
tensor_rank = tf.size(fill_tensor)
tensor_rank 


<tf.Tensor: shape=(), dtype=int32, numpy=90>

In [63]:
reandowm_tensor = tf.random.normal(
    [3,4],
    mean=0.0,
    stddev=2.0,
    seed= 5
)
reandowm_tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-2.3561656 , -1.4198828 , -3.496316  , -0.9907444 ],
       [ 0.48607776, -0.25262603, -1.3278574 , -0.99039674],
       [-1.7878686 , -3.593185  ,  0.8177471 , -2.403319  ]],
      dtype=float32)>

In [70]:
rend_uniform = tf.random.uniform(
    [3,5],
    maxval=10,
    minval=1,
)
rend_uniform

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1.2656835, 7.2408085, 2.997202 , 2.5689743, 6.51355  ],
       [9.565785 , 1.1287364, 5.7692747, 8.851347 , 6.408728 ],
       [7.290221 , 7.3349237, 7.2926073, 8.046528 , 1.3142079]],
      dtype=float32)>

In [ ]:
tensor_index = tf.constant([1, 24, 56, 78 ,9, 5,66])
print(tensor_index)
print(tensor_index[-1::])


tf.Tensor([ 1 24 56 78  9  5 66], shape=(7,), dtype=int32)
tf.Tensor([66], shape=(1,), dtype=int32)


In [93]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,4,5],
    [5,6,7],
])

print(tensor_two_d[..., 0])

tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [101]:
four_d_tensor = tf.constant([
#First layer 
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
],
[
    [1,2,3],
    [3,4,5],
    [5,6,7],
]]
)
print(tensor_three_d[0,...,0])

tf.Tensor([1 3], shape=(2,), dtype=int32)


In [104]:
x_abs = tf.constant([-2.25,3.25])
print(tf.abs(x_abs))

tf.Tensor([2.25 3.25], shape=(2,), dtype=float32)


In [106]:
x_abs_comp = tf.constant([-2.25 +3.25j])
print(tf.abs(x_abs_comp))



tf.Tensor([3.95284708], shape=(1,), dtype=float64)


In [108]:
x_1 = tf.constant([-2.25,3.25])
x_2 = tf.constant([6,23.25])
print(tf.add(x_1,x_2))

tf.Tensor([ 3.75 26.5 ], shape=(2,), dtype=float32)


In [118]:
x_args = tf.constant([[[2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,4, 5, 9, 71]
],
[                     [2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,102, 5, 9, 71]
]

])
print(tf.argmax(x_args,1))

tf.Tensor(
[[1 1 1 0 2 2]
 [1 1 2 0 2 2]], shape=(2, 6), dtype=int64)


In [ ]:
power = tf.constant([[2, 3, 4, 5, 6,7],
                      [5, 6, 22, 4, 5,6],
                      [1 ,2 ,4, 5, 9, 71]
])
print(x_pow = tf.pow(power,2))