In [1]:
import tensorflow as tf
import numpy as np

In [6]:
tensor_3d = tf.constant([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(tf.expand_dims(tensor_3d,axis=1))
print(tf.squeeze)

tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(2, 1, 3, 4), dtype=int32)
<function squeeze_v2 at 0x3244259e0>
